defaults:
  - _self_
  - dataset: paf
  - model: default
  - trainer: default
  - validator: default
  - tester: default
  - preprocessing: default
  - feature_extractors: default
  - plotters : default
  

seed: 42
split:
  train: 0.7
  val: 0.1
  test: 0.2
device:
  _target_: Device.Device
  device: "cuda"  # or "cpu"

# model:
#   - _target_: Model.CPCPreModel.CPCPreModel