_target_: Metadata.FileLoaderMetadata
name: "PAF Dataset"
path: "/Users/yasantha-mac/Downloads/paf-prediction-challenge-database-1.0.0"
file_names:
    - "p02"
    - "p04"
    - "p06"
    - "p08"
    - "p10"
    - "p12"
    - "p14"
    - "p16"
    - "p18"
    - "p20"
    - "p22"
    - "p24"
    - "p26"
    - "p28"
    - "p30"
    - "p32"
    - "p34"
    - "p36"
    - "p38"
    - "p40"
    - "p42"
    - "p44"
    - "p46"
    - "p48"
    - "p50"